import type { Metadata } from 'next'
import {Kalam } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import {Antonio} from 'next/font/google'


const antonio = Antonio({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-antonio',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Olymphia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  
    <html lang="en">
      <body className={antonio.className}>
        <Navbar/>

        {children}</body>
    </html>
    
  )
}
